on:
  push:
    branches:
      - '**'

name: Discord Notification

jobs:
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Discord Notifier
        uses: fateyan/action-discord-notifier@v1.2.0
        with:
          message-title: New Commits Pushed
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
